"""
Pydantic schemas for structured report output.
These models enforce validation on the Generation node's output,
ensuring every report conforms to the required structure.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class ForecastSummary(BaseModel):
    """Summary of the solar energy forecast for the analysis period."""

    period: str = Field(description="Forecast time period, e.g. '2025-01-15 to 2025-01-21'")
    avg_generation_kwh: float = Field(description="Average daily solar generation in kWh")
    peak_generation_kwh: float = Field(description="Peak hourly generation in kWh")
    min_generation_kwh: float = Field(description="Minimum hourly generation in kWh")
    variability_index: float = Field(
        description="Coefficient of variation (0-1) measuring forecast uncertainty"
    )
    trend: str = Field(description="Overall trend: INCREASING, DECREASING, or STABLE")
    confidence_level: float = Field(
        description="Model confidence as a percentage (0-100)"
    )


class RiskAnalysis(BaseModel):
    """Assessment of risks to grid stability from forecasted solar variability."""

    risk_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        description="Overall risk severity"
    )
    factors: list[str] = Field(
        description="List of specific risk factors identified"
    )
    mitigation_strategies: list[str] = Field(
        description="Recommended strategies to mitigate identified risks"
    )
    impact_assessment: str = Field(
        description="Narrative assessment of potential grid impact"
    )


class GridBalancingAction(BaseModel):
    """A specific action recommended for grid load balancing."""

    action_type: str = Field(
        description="Type of balancing action, e.g. 'Load Shifting', 'Curtailment'"
    )
    priority: Literal["IMMEDIATE", "SCHEDULED", "ADVISORY"] = Field(
        description="Action priority level"
    )
    description: str = Field(
        description="Detailed description of the recommended action"
    )
    expected_impact: str = Field(
        description="Expected impact on grid stability and efficiency"
    )
    timeframe: str = Field(
        description="When this action should be executed"
    )


class StorageRecommendation(BaseModel):
    """Battery storage charging/discharging recommendation."""

    action: Literal["CHARGE", "DISCHARGE", "HOLD"] = Field(
        description="Storage action to take"
    )
    target_soc_percent: float = Field(
        description="Target state of charge percentage (0-100)",
        ge=0,
        le=100,
    )
    reasoning: str = Field(
        description="Rationale behind this storage recommendation"
    )
    schedule: str = Field(
        description="Recommended time schedule for this action"
    )
    priority: Literal["HIGH", "MEDIUM", "LOW"] = Field(
        description="Priority of this storage action"
    )


class EnergyUtilizationPlan(BaseModel):
    """Comprehensive plan for energy allocation and demand management."""

    solar_allocation_percent: float = Field(
        description="Percentage of energy sourced from solar",
        ge=0,
        le=100,
    )
    grid_import_percent: float = Field(
        description="Percentage of energy imported from the grid",
        ge=0,
        le=100,
    )
    storage_usage_percent: float = Field(
        description="Percentage of energy drawn from storage",
        ge=0,
        le=100,
    )
    demand_response_actions: list[str] = Field(
        description="List of demand response actions to implement"
    )
    optimization_notes: str = Field(
        description="Additional optimization recommendations"
    )
    expected_cost_saving_percent: float = Field(
        description="Estimated cost savings from the plan as a percentage"
    )


class StructuredReport(BaseModel):
    """
    Complete structured report generated by the Solar Grid Optimization Agent.
    Contains all six required sections plus metadata.
    """

    forecast_summary: ForecastSummary
    risk_analysis: RiskAnalysis
    grid_balancing_actions: list[GridBalancingAction]
    storage_recommendations: list[StorageRecommendation]
    energy_utilization_plan: EnergyUtilizationPlan
    references: list[str] = Field(
        description="Cited RAG sources used to ground the recommendations"
    )
    generated_at: str = Field(
        description="ISO timestamp of report generation"
    )
    agent_version: str = Field(
        default="1.0.0",
        description="Version of the agent that generated this report"
    )
